version: "3"
services:
  web:
    image: ebm2018/teamy:latest
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb/teamy
    networks:
      local:
      ebm-filrouge:
        aliases:
          - teamy
    labels :
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:teamy.ebm.nymous.io"
      - "traefik.port=4000"
      - "traefik.network=ebm-filrouge"
      - "com.centurylinklabs.watchtower.enable=true"
  mongodb:
    image: mongo
    networks:
      - local
    volumes:
      - mongo-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "Teamy"
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
volumes:
  mongo-volume:
networks:
  local:
  ebm-filrouge:
    external: true
